package it.polimi.ingsw.Model.SchoolsMembers;

import it.polimi.ingsw.Model.Wizard.Wizard;

import java.io.Serializable;

/**
 *
 */
public class Professor implements Serializable {
    private static final long serialVersionUID = 5617884145379497150L;
    private final Color color;
    private Wizard property;
/**
 * @param color is the professor's color and is generated by the Enum Color
 * Professor(Color color) is the constructor of the Professor Class
 * */
    public Professor(Color color) {
        this.color = color;
    }
/**
 * @param property is used to tell which Wizard owns what
 * setProperty(Wizard property) is needed because the property changes a lot during the game*/
    public void setProperty(Wizard property) {
        this.property = property;
    }

    public Color getColor() {
        return color;
    }

    public Wizard getProperty() {
        return property;
    }

    @Override
    public String toString() {
        return "Professor{" +
                "color=" + color +
                '}';
    }
}
