package it.polimi.ingsw;

/**
 *
 */
public class Professor {
    private Color color;
    private Wizard property;
/**
 * @param color is the professor's color and is generated by the Enum Color
 * Professor(Color color) is the constructor of the Professor Class
 * */
    public Professor(Color color) {
        this.color = color;
    }
/**
 * @param property is used to tell which Wizard owns what
 * setProperty(Wizard property) is needed because the property changes a lot during the game*/
    public void setProperty(Wizard property) {
        this.property = property;
    }

    public Color getColor() {
        return color;
    }

    public Wizard getProperty() {
        return property;
    }
}
